@baseUrl = http://localhost:5000/api/debug

### GET /
GET {{baseUrl}}
Content-Type: application/json

### POST /generate
POST {{baseUrl}}/generate?temperature=0.9&top_p=1&max_length=100
Content-Type: application/json

{
    "prompt": "What would be a good company name a company that makes colorful socks?"
}

### POST /chat
POST {{baseUrl}}/chat
Content-Type: application/json

{
    "prompt": "Who am I? Who are you?",
    "messages": [
        { "role": "user", "content": "Hello, I am Mariocarter. Who are you?" },
        { "role": "assistant", "content": "Good day. I am your virtual assistant Lilith. How can I assist you today?" }
    ]
}

# {
#     "prompt": "Write me a song about sparkling water."
# }

### POST /sql/raw
POST {{baseUrl}}/sql/raw
Content-Type: application/json

{
    "prompt": "How many products do we have?"
}

### POST /sql/agent
POST {{baseUrl}}/sql/agent
Content-Type: application/json

{
    "prompt": "How many products do we have?"
}

### GET /stream/dummy (not supported in rest client atm, see https://github.com/Huachao/vscode-restclient/issues/493)
curl -X GET http://localhost:5000/api/debug/stream/dummy

### GET /stream/dummy/none
curl -X GET http://localhost:5000/api/debug/stream/dummy/none

### POST /stream
curl -X POST http://localhost:5000/api/debug/stream -H "Content-Type: application/json" -d '{"prompt": "Write me a song about sparkling water. In no more than 500 characters."}'
