@baseUrl = http://localhost:5000

### GET /api
GET {{baseUrl}}/api
Content-Type: application/json

### POST /api/generate
POST {{baseUrl}}/api/generate?temperature=0.9&top_p=1&max_length=100
Content-Type: application/json

{
    "prompt": "What would be a good company name a company that makes colorful socks?"
}

### POST /api/chat
POST {{baseUrl}}/api/chat
Content-Type: application/json

{
    "prompt": "Who am I? Who are you?",
    "messages": [
        { "role": "user", "content": "Hello, I am Mariocarter. Who are you?" },
        { "role": "assistant", "content": "Good day. I am your virtual assistant Lilith. How can I assist you today?" }
    ]
}

# {
#     "prompt": "Write me a song about sparkling water."
# }

### POST /api/sql/raw
POST {{baseUrl}}/api/sql/raw
Content-Type: application/json

{
    "prompt": "How many products do we have?"
}

### POST /api/sql/agent
POST {{baseUrl}}/api/sql/agent
Content-Type: application/json

{
    "prompt": "How many products do we have?"
}
